AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
  - 'db/migrate/*'

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Max: 100

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false
  
Layout/EmptyLinesAroundBeginBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantReturn:
  Enabled: false
